version: '3.8'

services:
  plantuml-server:
    image: plantuml/plantuml-server
    ports:
      - 8080:8080
  docs:
    image: sysl-docs
    volumes:
      - ./demo:/usr/demo
      - ./docs:/usr/docs
      - ./build.sh:/usr/build.sh

    environment:
      - SYSL_PLANTUML=http://plantuml-server:8080
      - OUTPUT_DIR=${OUTPUT_DIR}
    working_dir: /usr/
    entrypoint:
      - ./build.sh
    depends_on:
      - plantuml-server


