version: '3.8'

services:
  plantuml-server:
    image: plantuml/plantuml-server
    ports:
      - 8080:8080
  sysl-catalog:
    image: anzbank/sysl-catalog:latest
    volumes:
      - ./:/usr/demo/html
    environment:
      - SYSL_PLANTUML=http://plantuml-server:8080
    working_dir: /usr/demo/html
    entrypoint: ["./build.sh"]
    depends_on:
      - plantuml-server

