name: Build Docs
on:
  push:
    branches: [ master ]

jobs:
  gen-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Gen Docs
      run: make docker-compose
    - name: Commit docs
      uses: EndBug/add-and-commit@v4
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: push
      shell: bash
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}