name: Build Docs
on:
  push:
    branches: [ master ]

jobs:
  gen-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Gen Docs
      run: make docker-compose
    - name: git commit and push push
      if: "! contains(toJSON(github.event.commits.*.msg), '[skip-ci]')"
      run: git add -A && git commit -m "Update docs [skip-ci]"