name: Release

on:
  push:
    branches: [ master ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release-sysl-catalog:
    name: Release Sysl-Catalog
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
      - name: Build :latest
        run: docker build -t anzbank/sysl-catalog:latest .
      - name: Push to docker hub :latest
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: anzbank/sysl-catalog
          tag_with_ref: true
          add_git_labels: true
          tags: latest
          labels: org.opencontainers.image.revision=${{ github.sha }},org.opencontainers.image.url=https://sysl.io